### ISSUE TITLE
Blocks all traffic Mac OS X Seirra

### ISSUE THREAD

**Issue by Marachaun** [vpn-kill-switch/killswitch#19] opened 2019-10-02 01:33 UTC
Im kinda new to all this terminal stuff so im not sure how to fix this. When I connect to my vpn using  IPVanish the traffic is fine. Data in and out. When I use sudo killswitch -e I get the following: 

Jeremys-Mac-Pro:~ jeremyfreshour$ sudo killswitch -e
Interface  MAC address         IP
en2        44:d8:84:6d:8a:3f   10.0.0.19/8
utun1                          172.21.28.5

DNS leaking:
Public IP address (DNS): 64.145.93.14
Public IP address (WWW): 64.145.93.66
PEER IP address:   64.145.93.14

# --------------------------------------------------------------
# Loading rules
# --------------------------------------------------------------
No ALTQ support in kernel
ALTQ related functions disabled
block drop all
block drop out quick inet6 all
pass inet proto udp from any to 224.0.0.0/4 keep state
pass inet proto udp from 224.0.0.0/4 to any keep state
pass inet from any to 255.255.255.255 flags S/SA keep state
pass inet from 255.255.255.255 to any flags S/SA keep state
pass on en2 proto tcp from any port 67:68 to any port 67:68 flags S/SA keep state
pass on en2 proto udp from any port 67:68 to any port 67:68 keep state
pass on en2 inet proto tcp from any to 64.145.93.14 flags S/SA keep state
pass on en2 inet proto udp from any to 64.145.93.14 keep state
pass on utun1 all flags S/SA keep state

killswitch enabled

My conf is the default conf that comes with this. Ill post it anyway
Jeremys-Mac-Pro:~ jeremyfreshour$ sudo pfctl -Fa -f /tmp/killswitch.pf.conf -e
pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
0 tables deleted.
1 states cleared
source tracking entries cleared
pf: statistics cleared
pf: interface flags reset
pfctl: pf already enabled

after about 30 seconds the vpn disconnects and I can't connect to the net anymore. I turn off kill switch and it works just fine.

**Comment by nbari** [comment] 2019-10-02 08:02
hi @Marachaun that's indeed the normal behavior of the killswitch, what is strange is that your VPN goes down after 30 seconds, does this happens also when killswitch is off?  if not try to find the peer IP, check (https://vpn-kill-switch.com/post/pf/  and https://vpn-kill-switch.com/img/peerIP.jpg) 

Then pass the IP:

    killswitch -ip X.X.X.X

**Comment by Marachaun** [comment] 2019-10-02 08:18
I tried that... it still disconnects. I made sure ipvanishes kill switch is disabled. 

When I run 
sudo killswitch -e
I then run
Ping google.com
It hit the dns finds google but the pings fail

**Comment by Marachaun** [comment] 2019-10-02 08:18
Sorry, no the vpn stays up all day until I use killswitch

**Comment by nbari** [comment] 2019-10-02 08:29
Did you try adding your endpoint IP as mentioned before?

    killswitch -ip X.X.X.X

**Comment by Marachaun** [comment] 2019-10-02 08:31
Yes my peer ip is 64.145.93.20 I entered: sudo killswitch -ip 64.145.93.20 -e

30 seconds later the vpn goes down

**Comment by nbari** [comment] 2019-10-02 08:50
Probably is not the real endpoint IP address, by default `killswitch` try to find it for you, but in some cases (depends on the setup, multiple vpns, etc it must be specified)

The reason why your VPN goes down is that the killswitch is blocking traffic to peer IP you used to connect. 

After enabling the `killswitch` you could try to search for the `pflog0` interface and debug/check traffic been blocked:

    sudo tcpdump -n -e -ttt -i pflog0

I haven't tested on macOS but give a try, please update if find a way to dump/log the pf rules.

**Comment by nbari** [comment] 2019-10-04 12:34
Hi @Marachaun did you fix your problem or have any update? if you need help testing something please let me know.

**Comment by Marachaun** [comment] 2019-10-05 06:35
I haven’t figured it out. I don’t know enough about terminal commands and minipulating things in the terminal. Right now Im using IPVanish Kill switch. I’d rather it be at the hardware level but I can’t figure that one out.

**Comment by nbari** [comment] 2019-10-05 06:42
One of the main reasons for me to create `killswitch` was that the IPVanish app crashed and therefore the killswitch (http://vpn-kill-switch.com/about/). (the issue there could be just finding the peer IP)

at a hardware level, you could try a https://www.asuswrt-merlin.net or even better pfsense.org it is more complex but comes with its advantages.

**Comment by Marachaun** [comment] 2019-10-05 06:57
Jeremys-Mac-Pro:~ jeremyfreshour$ sudo killswitch -leak -ip 64.145.93.115 -e
Interface  MAC address         IP
en2        44:d8:84:6d:8a:3f   10.0.0.19/8
utun1                          172.21.28.16

DNS leaking:
Public IP address (DNS): 64.145.93.115
Public IP address (WWW): 64.145.93.146
PEER IP address:   64.145.93.115

# --------------------------------------------------------------
# Loading rules
# --------------------------------------------------------------
No ALTQ support in kernel
ALTQ related functions disabled
block drop all
block drop out quick inet6 all
pass quick proto tcp from any to any port = 53 flags S/SA keep state
pass quick proto udp from any to any port = 53 keep state
pass inet proto udp from any to 224.0.0.0/4 keep state
pass inet proto udp from 224.0.0.0/4 to any keep state
pass inet from any to 255.255.255.255 flags S/SA keep state
pass inet from 255.255.255.255 to any flags S/SA keep state
pass on en2 proto tcp from any port 67:68 to any port 67:68 flags S/SA keep state
pass on en2 proto udp from any port 67:68 to any port 67:68 keep state
pass on en2 inet proto icmp all icmp-type echoreq code 0 keep state
pass on en2 inet proto tcp from any to 64.145.93.115 flags S/SA keep state
pass on en2 inet proto udp from any to 64.145.93.115 keep state
pass on utun1 all flags S/SA keep state

killswitch enabled

// VPN Goes Down // 

Jeremys-Mac-Pro:~ jeremyfreshour$ sudo killswitch -leak -ip 64.145.93.115 -d
No ALTQ support in kernel
ALTQ related functions disabled
scrub-anchor "com.apple/*" all fragment reassemble
anchor "com.apple/*" all

killswitch disabled
Jeremys-Mac-Pro:~ jeremyfreshour$

**Comment by nbari** [comment] 2019-10-05 07:00
hi @Marachaun just for testing try `64.145.93.146`, how are you obtaining the peer IP ? try the one shown in the ipvanish app.

**Comment by Marachaun** [comment] 2019-10-05 07:04
The IPVanish tells you. Look at the picture. On the right hand side where it says connected to

It still kills the vpn.

**Comment by nbari** [comment] 2019-10-05 07:05
Try this with the VPN enabled:

    route get 0.0.0.0 2>/dev/null | awk '/interface: / {print $2}';

Then based on the output (probably utun1):

    ifconfig <interfacename>

**Comment by Marachaun** [comment] 2019-10-05 07:07
Jeremys-Mac-Pro:~ jeremyfreshour$ route get 0.0.0.0 2>/dev/null | awk '/interface: / {print $2}';
en2
Jeremys-Mac-Pro:~ jeremyfreshour$ ifconfig en2
en2: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 44:d8:84:6d:8a:3f 
	inet 10.0.0.19 netmask 0xffffff00 broadcast 10.0.0.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active

**Comment by nbari** [comment] 2019-10-05 07:11
Ok that doesn't look good you should have another interface, something like  `utun1 ` that interface gets created after creating/enabling the VPN, check your options/config to use UDP or TCP within the app, once you get the interface give a try again to enable the killswitch `killswitch -e` or by passing the peer ip`killswithc -ip X.X.X.X` -e `

**Comment by nbari** [comment] 2019-10-05 07:25
Hi @Marachaun normally you get a `utunX` interface, but it could be that you also get an  `ipsec0` instead wich is fine.

**Comment by Marachaun** [comment] 2019-10-05 07:31
Ive tested with both UDP and TCP neither give a utunX interface. Only en2 which is my wireless

**Comment by nbari** [comment] 2019-10-05 07:45
I think that the VPN is not properly configured since it should modify your routes to be the default one and send all traffic through it (even before using the killswitch)

If you do an `ifconfig -a` when the VPN is enabled, you may see the `utun1` interface, but for some reason is not sending traffic through the VPN, that's why when you enable the `killswitch` it goes down, you could also try having the VPN enabled and then run:

    netstat -rna -f inet
 
The interface of your VPN should be on top, give a try reinstalling the app or check the settings, an easy way to check is to run:

     route get 0.0.0.0 

Until it doesn't print the VPN interface (other than en1 or en2), the killswitch won't work.

**Comment by Marachaun** [comment] 2019-10-05 08:08
Jeremys-Mac-Pro:~ jeremyfreshour$ ifconfig en2
en2: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 44:d8:84:6d:8a:3f 
	inet 10.0.0.19 netmask 0xffffff00 broadcast 10.0.0.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
Jeremys-Mac-Pro:~ jeremyfreshour$ ifconfig utun1
ifconfig: interface utun1 does not exist
Jeremys-Mac-Pro:~ jeremyfreshour$ ifconfig utun0
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::4a3a:b2a1:35e0:480b%utun0 prefixlen 64 scopeid 0x11 
	nd6 options=201<PERFORMNUD,DAD>
Jeremys-Mac-Pro:~ jeremyfreshour$

**Comment by Marachaun** [comment] 2019-10-05 08:13
Last login: Sat Oct  5 02:03:21 on ttys000
Jeremys-Mac-Pro:~ jeremyfreshour$ route get 0.0.0.0 2>/dev/null | awk '/interface: / {print $2}';
en2
Jeremys-Mac-Pro:~ jeremyfreshour$ ifconfig en2
en2: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 44:d8:84:6d:8a:3f 
	inet 10.0.0.19 netmask 0xffffff00 broadcast 10.0.0.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
Jeremys-Mac-Pro:~ jeremyfreshour$ ifconfig utun1
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 172.21.22.110 --> 172.21.22.110 netmask 0xfffffe00 
Jeremys-Mac-Pro:~ jeremyfreshour$ ifconfig utun0
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::4a3a:b2a1:35e0:480b%utun0 prefixlen 64 scopeid 0x11 
	nd6 options=201<PERFORMNUD,DAD>
Jeremys-Mac-Pro:~ jeremyfreshour$

**Comment by nbari** [comment] 2019-10-05 08:19
hi @Marachaun the problem is that when you enable the VPN its  interface should become the default gateway, check it with:

     route get 0.0.0.0

For some reason, in your case is not doing it, you should see something like:

```
$ route get 0.0.0.0
   route to: default
destination: default
       mask: default
  interface: ipsec0
      flags: <UP,DONE,CLONING,STATIC>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1400         0
```

In this example the interface in use is `ipsec0` but can be `utun1` etc but not your local interfaces like `en1`, `en2` etc

**Comment by Marachaun** [comment] 2019-10-05 08:22
Yes min just says en2. But I’ve reinstalled ipvanish twice and tried OpenVPN TCP and UDP

**Comment by Marachaun** [comment] 2019-10-05 08:25
The VPN is woking, it is redirecting my ip. For example I go to whatismyip.com <http://whatismyip.com/> on my phone I get my public ip. I go to the same site on my Mac it comes with a different ip that IPVanish assigned

**Comment by nbari** [comment] 2019-10-05 08:32
Yes, VPN is working but probably leaking, that's why when enabling the `killswitch` or force trafic to go only through the VPN it goes down, they may be using your `enX` interface to do other checks instead of doing them through the tunnel 

I currently don't have an account with them but when tested years ago routes where added, will need to further test.

**Comment by nbari** [comment] 2020-03-04 08:13
I am closing this for now, feel free to re-open it if needed.

**Closed by nbari** 2020-03-04 08:13 UTC
Labels: hacktoberfest, help wanted
